# Generated by Django 3.1.1 on 2020-09-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
