# Generated by Django 3.0.8 on 2020-08-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_timestamp'),
        ('products', '0004_auto_20190910_1908'),
        ('products', '0006_auto_20190917_1913'),
    ]

    operations = [
    ]
