# Generated by Django 3.0.8 on 2020-08-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200801_0031'),
        ('orders', '0003_auto_20170929_0013'),
    ]

    operations = [
    ]
