# Generated by Django 3.1.1 on 2020-09-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='order_id',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
